# ALACRITTY CONFIG FILE

import = [
"~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
	padding = { x = 16, y = 16 }
	dynamic_padding = true
	opacity = 0.85
	blur = true
[font]
	normal = { family = "Hack", style = "Regular" }
	size = 9

